version: "3.8"

services:
  ui:
    build: ./ui
    env_file: ".env"
    ports:
      - ${UI_PORT}:${UI_PORT}
    volumes:
      - ./ui:/app/ui

  api:
    build: ./api
    env_file: ".env"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app/api
